### ISSUE TITLE
Objective-c?

### ISSUE THREAD

**Issue by JillianJM** [azurechen/ACTabScrollView#1]
Is the scrollview available in objective-c? I could only find the swift project, it looks very good, was hoping to find its objective-c flavour.

**Comment by azurechen** [comment]
Hi JillianJM,

You can refer to [Swift and Objective-C in the Same Project](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html) and find `Importing Swift into Objective-C` section.

I will add an example in objective-c to the README.md file later. And if that resolve your problem, please give us a star! Thank you!

**Comment by azurechen** [comment]
I have update the README file and add a chapter about [Using ACTabScrollView in Objective-C Project](https://github.com/azurechen/ACTabScrollView#using-actabscrollview-in-objective-c-project)

Thank you!

**Comment by JillianJM** [comment]
Thank you.

On Sat, Jun 18, 2016 at 10:38 PM, Azure Chen notifications@github.com
wrote:

> Closed #1 https://github.com/azurechen/ACTabScrollView/issues/1.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/azurechen/ACTabScrollView/issues/1#event-696770596,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARS9zjR8EWPpOCaOxPllgMGaH0IK7rVJks5qNCYrgaJpZM4Iuv_7
> .

## 

Thank You!
Jillian

Vice President - Customer Success
Picsean Media - www.picsean.com
