### ISSUE TITLE
Pull-to-Refresh 

### ISSUE THREAD

**Issue by silviocolman** [azurechen/ACTabScrollView#17]
Good, as it could do to add to the tableview a pull to refresh or where in the same should write the code to do that ?. I'm programming in swift 3

**Comment by azurechen** [comment]
Hi silviocolman,
`Pull to refresh` and `Tableview` are not related to the library. You can add this function in your sub `UIViewController`'s.
Use the built-in `UIRefreshControl` to implement this function is very easy. Or you can find some brilliant 3-party libraries at Github.
