### ISSUE TITLE
how to move TabBar from Top to Bottom

### ISSUE THREAD

**Issue by surender2906** [azurechen/ACTabScrollView#18]
I want to show same view but change a little bit 
move tabbar from Top to Bottom.
I am waiting for your kind response.

**Comment by azurechen** [comment]
Hi surender2906,

This feature is in my future plan, but if you have figured out how to modify it.
Welcome to contribute to this project together.

Maybe you already notice that 2 lines in `setupPages` function of `ACTabScrollView.swift`
```
tabSectionScrollView.frame = CGRect(x: 0, y: 0, width: self.frame.size.width, height: tabSectionHeight)
```
```
contentSectionScrollView.frame = CGRect(x: 0, y: tabSectionHeight, width: self.frame.size.width, height: contentSectionHeight)
```
Just change the `y` value can move tab bar from top to bottom
