### ISSUE TITLE
Disable scroll gesture setting

### ISSUE THREAD

**Issue by Minitour** [azurechen/ACTabScrollView#4]
Is it possible to disable the scroll gesture and have the tab scroll using touch-up-inside through the tabs? What I am asking is if it is possible to get rid of the gesture so the user will not scroll between views by swiping.

**Comment by DaniArnaout** [comment]
@Minitour Sure you can.
I'll submit a PR shortly with the options to turn scrolling on tab section on/off.

Meanwhile, you can hack it by adding this property to your ACTabSCrollView.swift file.

```
    @IBInspectable public var tabSectionScrollEnabled: Bool = true {
      didSet {
       tabSectionScrollView.scrollEnabled = tabSectionScrollEnabled
      }
    }
```

This way you'll be able to set `tabSectionScrollEnabled` to false on your `ACTabSCrollView` instance and have it work like a charm.

**Comment by Minitour** [comment]
Thanks for the suggestion @DaniArnaout.

**Comment by azurechen** [comment]
Thank you @DaniArnaout ! Good suggestion!
And Thank you @Minitour for your feedback!

Recently I am busy in my job, but it is exciting that somebody use my library to build great things!
I will keep improve this library later and welcome any PR

Thank you very much!
